// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GameStatus string

const (
	GameStatusWaiting    GameStatus = "waiting"
	GameStatusInProgress GameStatus = "in_progress"
	GameStatusCompleted  GameStatus = "completed"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus `json:"game_status"`
	Valid      bool       `json:"valid"` // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

func (e GameStatus) Valid() bool {
	switch e {
	case GameStatusWaiting,
		GameStatusInProgress,
		GameStatusCompleted:
		return true
	}
	return false
}

func AllGameStatusValues() []GameStatus {
	return []GameStatus{
		GameStatusWaiting,
		GameStatusInProgress,
		GameStatusCompleted,
	}
}

type PlayerRole string

const (
	PlayerRoleParticipant PlayerRole = "participant"
	PlayerRoleHost        PlayerRole = "host"
)

func (e *PlayerRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerRole(s)
	case string:
		*e = PlayerRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerRole: %T", src)
	}
	return nil
}

type NullPlayerRole struct {
	PlayerRole PlayerRole `json:"player_role"`
	Valid      bool       `json:"valid"` // Valid is true if PlayerRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerRole) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerRole), nil
}

func (e PlayerRole) Valid() bool {
	switch e {
	case PlayerRoleParticipant,
		PlayerRoleHost:
		return true
	}
	return false
}

func AllPlayerRoleValues() []PlayerRole {
	return []PlayerRole{
		PlayerRoleParticipant,
		PlayerRoleHost,
	}
}

type Game struct {
	ID          uuid.UUID        `json:"id"`
	HostID      uuid.UUID        `json:"host_id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Theme       *string          `json:"theme"`
	Status      NullGameStatus   `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	FinishedAt  pgtype.Timestamp `json:"finished_at"`
}

type GameConfiguration struct {
	ID                 uuid.UUID        `json:"id"`
	GameID             uuid.UUID        `json:"game_id"`
	TimePerQuestion    *int32           `json:"time_per_question"`
	RandomizeQuestions *bool            `json:"randomize_questions"`
	StreakMultiplier   *int32           `json:"streak_multiplier"`
	StreakStart        *int32           `json:"streak_start"`
	RoomSize           *int32           `json:"room_size"`
	QuestionsCount     *int32           `json:"questions_count"`
	Prompt             []byte           `json:"prompt"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type GameEvent struct {
	ID        uuid.UUID        `json:"id"`
	GameID    uuid.UUID        `json:"game_id"`
	EventType string           `json:"event_type"`
	EventData []byte           `json:"event_data"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type GameQuestion struct {
	ID            uuid.UUID `json:"id"`
	GameID        uuid.UUID `json:"game_id"`
	QuestionID    uuid.UUID `json:"question_id"`
	QuestionOrder int32     `json:"question_order"`
}

type GameRound struct {
	ID          uuid.UUID        `json:"id"`
	GameID      uuid.UUID        `json:"game_id"`
	RoundNumber int32            `json:"round_number"`
	StartedAt   pgtype.Timestamp `json:"started_at"`
	EndedAt     pgtype.Timestamp `json:"ended_at"`
}

type GameRoundAnswer struct {
	ID             uuid.UUID        `json:"id"`
	RoundID        uuid.UUID        `json:"round_id"`
	PlayerID       uuid.UUID        `json:"player_id"`
	QuestionID     uuid.UUID        `json:"question_id"`
	SelectedOption int32            `json:"selected_option"`
	IsCorrect      bool             `json:"is_correct"`
	AnsweredAt     pgtype.Timestamp `json:"answered_at"`
}

type GameScore struct {
	ID             uuid.UUID        `json:"id"`
	PlayerID       uuid.UUID        `json:"player_id"`
	GameID         uuid.UUID        `json:"game_id"`
	Score          *int32           `json:"score"`
	CorrectAnswers *int32           `json:"correct_answers"`
	TotalQuestions *int32           `json:"total_questions"`
	Position       *int32           `json:"position"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Guest struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	SessionToken string           `json:"session_token"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Player struct {
	ID                uuid.UUID        `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	GuestID           pgtype.UUID      `json:"guest_id"`
	TotalQuizzesTaken *int32           `json:"total_quizzes_taken"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type PlayerGame struct {
	ID          uuid.UUID        `json:"id"`
	PlayerID    uuid.UUID        `json:"player_id"`
	GameID      uuid.UUID        `json:"game_id"`
	Role        NullPlayerRole   `json:"role"`
	JoinedAt    pgtype.Timestamp `json:"joined_at"`
	LeftAt      pgtype.Timestamp `json:"left_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type Question struct {
	ID            uuid.UUID        `json:"id"`
	Content       string           `json:"content"`
	Options       []byte           `json:"options"`
	CorrectOption int32            `json:"correct_option"`
	Explanation   *string          `json:"explanation"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type QuestionTag struct {
	QuestionID uuid.UUID        `json:"question_id"`
	TagID      uuid.UUID        `json:"tag_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Tag struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	Username  string           `json:"username"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Icon      *string          `json:"icon"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
