// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================
	// PLAYER_GAMES QUERIES
	// ============================================
	AddPlayerToGame(ctx context.Context, arg AddPlayerToGameParams) (PlayerGame, error)
	// ============================================
	// GAME_QUESTIONS QUERIES
	// ============================================
	AddQuestionToGame(ctx context.Context, arg AddQuestionToGameParams) (GameQuestion, error)
	// ============================================
	// QUESTION_TAGS QUERIES
	// ============================================
	AddTagToQuestion(ctx context.Context, arg AddTagToQuestionParams) error
	CompletePlayerGame(ctx context.Context, arg CompletePlayerGameParams) error
	CountCorrectAnswersInRound(ctx context.Context, arg CountCorrectAnswersInRoundParams) (int64, error)
	CountGameQuestions(ctx context.Context, gameID uuid.UUID) (int64, error)
	CountGameRounds(ctx context.Context, gameID uuid.UUID) (int64, error)
	CountGames(ctx context.Context) (int64, error)
	CountGamesByStatus(ctx context.Context, status NullGameStatus) (int64, error)
	CountPlayerAnswersInRound(ctx context.Context, arg CountPlayerAnswersInRoundParams) (int64, error)
	CountPlayers(ctx context.Context) (int64, error)
	CountPlayersInGame(ctx context.Context, gameID uuid.UUID) (int64, error)
	CountQuestions(ctx context.Context) (int64, error)
	CountQuestionsByTag(ctx context.Context, tagID uuid.UUID) (int64, error)
	CountTags(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ============================================
	// GAMES QUERIES
	// =============================================
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	// ============================================
	// GAME_CONFIGURATIONS QUERIES
	// ============================================
	CreateGameConfiguration(ctx context.Context, arg CreateGameConfigurationParams) (GameConfiguration, error)
	// ============================================
	// GAME_EVENTS QUERIES
	// ============================================
	CreateGameEvent(ctx context.Context, arg CreateGameEventParams) (GameEvent, error)
	// ============================================
	// GAME_ROUND QUERIES
	// ============================================
	CreateGameRound(ctx context.Context, arg CreateGameRoundParams) (GameRound, error)
	// ============================================
	// GAME_ROUND_ANSWERS QUERIES
	// ============================================
	CreateGameRoundAnswer(ctx context.Context, arg CreateGameRoundAnswerParams) (GameRoundAnswer, error)
	// ============================================
	// GAME_SCORES QUERIES
	// ============================================
	CreateGameScore(ctx context.Context, arg CreateGameScoreParams) (GameScore, error)
	// ============================================
	// GUESTS QUERIES
	// ============================================
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	CreatePlayerFromGuest(ctx context.Context, guestID pgtype.UUID) (Player, error)
	// ============================================
	// PLAYERS QUERIES
	// ============================================
	CreatePlayerFromUser(ctx context.Context, userID pgtype.UUID) (Player, error)
	// ============================================
	// QUESTIONS QUERIES
	// ============================================
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	// ============================================
	// TAGS QUERIES
	// ============================================
	CreateTag(ctx context.Context, name string) (Tag, error)
	// ============================================
	// USER QUERIES
	// =============================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGame(ctx context.Context, id uuid.UUID) error
	DeleteGameConfiguration(ctx context.Context, gameID uuid.UUID) error
	DeleteGameEvent(ctx context.Context, id uuid.UUID) error
	DeleteGameEvents(ctx context.Context, gameID uuid.UUID) error
	DeleteGameQuestions(ctx context.Context, gameID uuid.UUID) error
	DeleteGameRound(ctx context.Context, id uuid.UUID) error
	DeleteGameRoundAnswer(ctx context.Context, id uuid.UUID) error
	DeleteGameScore(ctx context.Context, arg DeleteGameScoreParams) error
	DeleteGuest(ctx context.Context, id uuid.UUID) error
	DeletePlayer(ctx context.Context, id uuid.UUID) error
	DeletePlayerGame(ctx context.Context, arg DeletePlayerGameParams) error
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteQuestionTags(ctx context.Context, questionID uuid.UUID) error
	DeleteRoundAnswers(ctx context.Context, roundID uuid.UUID) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	EndGameRound(ctx context.Context, id uuid.UUID) (GameRound, error)
	FinishGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetCurrentGameRound(ctx context.Context, gameID uuid.UUID) (GameRound, error)
	GetGameByID(ctx context.Context, id uuid.UUID) (Game, error)
	GetGameConfiguration(ctx context.Context, gameID uuid.UUID) (GameConfiguration, error)
	GetGameEvent(ctx context.Context, id uuid.UUID) (GameEvent, error)
	GetGameQuestion(ctx context.Context, id uuid.UUID) (GameQuestion, error)
	GetGameQuestionByOrder(ctx context.Context, arg GetGameQuestionByOrderParams) (GetGameQuestionByOrderRow, error)
	GetGameRound(ctx context.Context, id uuid.UUID) (GameRound, error)
	GetGameRoundAnswer(ctx context.Context, id uuid.UUID) (GameRoundAnswer, error)
	GetGameRoundByNumber(ctx context.Context, arg GetGameRoundByNumberParams) (GameRound, error)
	GetGameScore(ctx context.Context, arg GetGameScoreParams) (GameScore, error)
	GetGameScoreWithPlayerInfo(ctx context.Context, arg GetGameScoreWithPlayerInfoParams) (GetGameScoreWithPlayerInfoRow, error)
	GetGameWithHost(ctx context.Context, id uuid.UUID) (GetGameWithHostRow, error)
	GetGuestByID(ctx context.Context, id uuid.UUID) (Guest, error)
	GetGuestBySessionToken(ctx context.Context, sessionToken string) (Guest, error)
	GetPlayerAnswer(ctx context.Context, arg GetPlayerAnswerParams) (GameRoundAnswer, error)
	GetPlayerByGuestID(ctx context.Context, guestID pgtype.UUID) (Player, error)
	GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error)
	GetPlayerByUserID(ctx context.Context, userID pgtype.UUID) (Player, error)
	GetPlayerGame(ctx context.Context, arg GetPlayerGameParams) (PlayerGame, error)
	GetPlayerStats(ctx context.Context, id uuid.UUID) (GetPlayerStatsRow, error)
	GetPlayerWithUserInfo(ctx context.Context, id uuid.UUID) (GetPlayerWithUserInfoRow, error)
	GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	GetQuestionWithTags(ctx context.Context, questionID uuid.UUID) (GetQuestionWithTagsRow, error)
	GetRoundStatistics(ctx context.Context, roundID uuid.UUID) (GetRoundStatisticsRow, error)
	GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTopScores(ctx context.Context, limitVal int32) ([]GetTopScoresRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	HardDeleteUser(ctx context.Context, id uuid.UUID) error
	IncrementGameScore(ctx context.Context, arg IncrementGameScoreParams) (GameScore, error)
	ListGameEvents(ctx context.Context, arg ListGameEventsParams) ([]GameEvent, error)
	ListGameEventsByType(ctx context.Context, arg ListGameEventsByTypeParams) ([]GameEvent, error)
	ListGameQuestions(ctx context.Context, gameID uuid.UUID) ([]ListGameQuestionsRow, error)
	ListGameRounds(ctx context.Context, gameID uuid.UUID) ([]GameRound, error)
	ListGameScores(ctx context.Context, gameID uuid.UUID) ([]ListGameScoresRow, error)
	ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error)
	ListGamesByPlayer(ctx context.Context, arg ListGamesByPlayerParams) ([]ListGamesByPlayerRow, error)
	ListGuests(ctx context.Context, arg ListGuestsParams) ([]Guest, error)
	ListPlayerAnswersInRound(ctx context.Context, arg ListPlayerAnswersInRoundParams) ([]ListPlayerAnswersInRoundRow, error)
	ListPlayerScores(ctx context.Context, arg ListPlayerScoresParams) ([]ListPlayerScoresRow, error)
	ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error)
	ListPlayersInGame(ctx context.Context, gameID uuid.UUID) ([]ListPlayersInGameRow, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error)
	ListRoundAnswers(ctx context.Context, roundID uuid.UUID) ([]ListRoundAnswersRow, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemovePlayerFromGame(ctx context.Context, arg RemovePlayerFromGameParams) error
	RemoveQuestionFromGame(ctx context.Context, arg RemoveQuestionFromGameParams) error
	RemoveTagFromQuestion(ctx context.Context, arg RemoveTagFromQuestionParams) error
	ReorderGameQuestions(ctx context.Context, arg ReorderGameQuestionsParams) error
	SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]User, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	StartGame(ctx context.Context, id uuid.UUID) (Game, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpdateGameConfiguration(ctx context.Context, arg UpdateGameConfigurationParams) (GameConfiguration, error)
	UpdateGameScore(ctx context.Context, arg UpdateGameScoreParams) (GameScore, error)
	UpdateGameScorePosition(ctx context.Context, arg UpdateGameScorePositionParams) error
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (Game, error)
	UpdatePlayerQuizzesTaken(ctx context.Context, id uuid.UUID) error
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
